server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**, 
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveryInfos/**, 
        - id: storage
          uri: http://localhost:8083
          predicates:
            - Path=/itemStorages/**, 
        - id: notify
          uri: http://localhost:8084
          predicates:
            - Path=, 
        - id: infomation
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**, 
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveryInfos/**, 
        - id: storage
          uri: http://storage:8080
          predicates:
            - Path=/itemStorages/**, 
        - id: notify
          uri: http://notify:8080
          predicates:
            - Path=, 
        - id: infomation
          uri: http://infomation:8080
          predicates:
            - Path=, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
